div '.copyright', 'Copyright © 2011, Dawn Lisa Borowski'
div '.phone', '(973) 332-1559'
div '.ionways', -> a href: 'http://ionwayspro.com/healthcoach', -> 'ionwayspro.com/healthcoach'
div '.newchapter', -> a href: 'http://newchapter.com', -> 'newchapter.com'
div '.contact', -> a href: '/contact.html', -> 'Contact Me'
